#!/bin/sh

git config --global core.autocrlf input
git config --global init.defaultBranch main
git config --global user.name "Wayne Maurer"
git config --global user.email 2899448+wmaurer@users.noreply.github.com

